name: Release
run-name: Build & Release
on:
  push:
    branches:
      - 'release-**'
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: latest

  #     - uses: pnpm/action-setup@v3
  #       name: Setup pnpm
  #       with:
  #         version: 8

  #     - name: Install deppendencies
  #       run: pnpm install

  #     - name: Build
  #       run: pnpm run build

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: connect to machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SHH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ private.SSH_KEY }}
          script: whoami
