name: Release
run-name: Build & Release
on:
  push:
    branches:
      - 'release-**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
          with:
            version: 8

      - name: Install deppendencies
        run: pnpm ci

      - name: Build
        run: pnpm run build

  # deploy:
  #   needs: [build]
