name: Release
run-name: Build & Release
on:
  push:
    branches:
      - 'release-**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm run build

  # deploy:
  #   needs: [build]
